//Ecrit par Khalil Arrahmen Bouraoui a partir du script generer par DataModeler du fichier <<ModeleLogique projet.dmd>>

/*DROP TABLE EMPRUNT;
DROP TABLE LIVRE;
DROP TABLE AUTEUR;
DROP TABLE ETAT;
DROP TABLE MAISONEDITION;
DROP TABLE GENRE;
DROP TABLE SUSPENSIONS;
DROP TABLE MEMBRE;
DROP TABLE STATUS;
DROP TABLE ADRESSE;
DROP TABLE DROIT;
DROP TABLE ROLE;
DROP TABLE "session";
DROP TABLE UTILISATEUR;*/


//Partie1: utilisateur,session,role,droit
CREATE TABLE utilisateur (
    idutilisateur INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nomutilisateur VARCHAR2(64 CHAR) NOT NULL,
    motdepasse     VARCHAR2(64) NOT NULL
  );
  
CREATE TABLE "session" (
    idsession                 INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    utilisateur_idutilisateur INTEGER NOT NULL,
    
    CONSTRAINT session_utilisateur_fk FOREIGN KEY (utilisateur_idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE role (
    idrole                    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nomrole                   VARCHAR2(64) NOT NULL,
    utilisateur_idutilisateur INTEGER NOT NULL,
    
    CONSTRAINT role_utilisateur_fk FOREIGN KEY ( utilisateur_idutilisateur ) REFERENCES utilisateur ( idutilisateur ) ON DELETE CASCADE
);

CREATE TABLE droit (
    iddroit     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_idrole INTEGER NOT NULL,
    
    CONSTRAINT droit_role_fk FOREIGN KEY ( role_idrole ) REFERENCES role ( idrole ) ON DELETE CASCADE
);


//Partie2: membre,adresse,status,suspensions
CREATE TABLE adresse (
    idadresse        INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    numerodebatiment INTEGER NOT NULL,
    nomderue         VARCHAR2(64 CHAR) NOT NULL,
    codepostale      VARCHAR2(64 CHAR) NOT NULL
);

CREATE TABLE status (
    idstatus INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom      VARCHAR2(64 CHAR) NOT NULL
);

CREATE TABLE membre (
    idmembre          INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom               VARCHAR2(64 CHAR) NOT NULL,
    prenom            VARCHAR2(64 CHAR) NOT NULL,
    numerotelephone   VARCHAR2(20 CHAR) NOT NULL,
    adressecourriel   VARCHAR2(100 CHAR) NOT NULL,
    dateabonnement    DATE NOT NULL,
    status_idstatus   INTEGER NOT NULL,
    adresse_idadresse INTEGER NOT NULL,
    
    CONSTRAINT membre_adresse_fk FOREIGN KEY ( adresse_idadresse ) REFERENCES adresse ( idadresse ) ON DELETE CASCADE,
    CONSTRAINT membre_status_fk FOREIGN KEY ( status_idstatus ) REFERENCES status ( idstatus ) ON DELETE CASCADE
);

CREATE TABLE suspensions (
    idsuspension    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    datedebut       DATE NOT NULL,
    datefin         DATE,
    raison          VARCHAR2(256 CHAR) NOT NULL,
    membre_idmembre INTEGER NOT NULL,
    
    CONSTRAINT suspensions_membre_fk FOREIGN KEY ( membre_idmembre ) REFERENCES membre ( idmembre ) ON DELETE CASCADE
);


//Partie3:genre,maisonEdition,etat,auteur,livre
CREATE TABLE genre (
    idgenre INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom     VARCHAR2(64 CHAR) NOT NULL
);

CREATE TABLE maisonedition (
    idme INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom  VARCHAR2(64) NOT NULL
);

CREATE TABLE etat (
    idetat  INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nometat VARCHAR2(64 CHAR) NOT NULL
);

CREATE TABLE auteur (
    idauteur INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom      VARCHAR2(64 CHAR) NOT NULL
);

CREATE TABLE livre (
    idlivre            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    titre              VARCHAR2(256 CHAR) NOT NULL,
    datepublication    DATE NOT NULL,
    numeroisbn         INTEGER,
    description        VARCHAR2(256 CHAR) NOT NULL,
    cheminimagecouverture    VARCHAR2(256 CHAR) NOT NULL,
    estemprunte       NUMBER NOT NULL,
    genre_idgenre      INTEGER NOT NULL,
    auteur_idauteur    INTEGER NOT NULL,
    etat_idetat        INTEGER NOT NULL,
    maisonedition_idme INTEGER NOT NULL,
    
    CONSTRAINT livre_genre_fk FOREIGN KEY ( genre_idgenre ) REFERENCES genre ( idgenre ) ON DELETE CASCADE,
    CONSTRAINT livre_auteur_fk FOREIGN KEY ( auteur_idauteur ) REFERENCES auteur ( idauteur ) ON DELETE CASCADE,
    CONSTRAINT livre_etat_fk FOREIGN KEY ( etat_idetat ) REFERENCES etat ( idetat ) ON DELETE CASCADE,
    CONSTRAINT livre_maisonedition_fk FOREIGN KEY ( maisonedition_idme ) REFERENCES maisonedition ( idme ) ON DELETE CASCADE
);


//Partie4:emprunt
CREATE TABLE emprunt (
    idemprunt                 INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    membre_idmembre           INTEGER NOT NULL,
    livre_idlivre             INTEGER NOT NULL,
    datedebut                 DATE NOT NULL,
    dateretourprevue          DATE NOT NULL,
    dateretour                DATE,
    enretard                  NUMBER NOT NULL,
    utilisateur_idutilisateur INTEGER NOT NULL,
    
    CONSTRAINT emprunt_livre_fk FOREIGN KEY ( livre_idlivre ) REFERENCES livre ( idlivre ) ON DELETE CASCADE,
    CONSTRAINT emprunt_membre_fk FOREIGN KEY ( membre_idmembre ) REFERENCES membre ( idmembre ) ON DELETE CASCADE,
    CONSTRAINT emprunt_utilisateur_fk FOREIGN KEY ( utilisateur_idutilisateur ) REFERENCES utilisateur ( idutilisateur ) ON DELETE CASCADE
);


//Partie5:peuplement de la base

INSERT INTO utilisateur(nomutilisateur,motdepasse)
VALUES ('employe1','emp1');
INSERT INTO utilisateur(nomutilisateur,motdepasse)
VALUES ('employe2','emp2');
INSERT INTO utilisateur(nomutilisateur,motdepasse)
VALUES ('employe3','emp3');

INSERT INTO "session"(utilisateur_idutilisateur)
VALUES(SELECT idutilisateur from utilisateur where nomutilisateur='employe2');
INSERT INTO "session"(utilisateur_idutilisateur)
VALUES(SELECT idutilisateur from utilisateur where nomutilisateur='employe3');
INSERT INTO "session"(utilisateur_idutilisateur)
VALUES(SELECT idutilisateur from utilisateur where nomutilisateur='employe1');

INSERT INTO role(nomrole, utilisateur_idutilisateur)
VALUES('RoleBoss',(SELECT idutilisateur from utilisateur where nomutilisateur='employe1'));
INSERT INTO role(nomrole, utilisateur_idutilisateur)
VALUES('RoleResponsable1',(SELECT idutilisateur from utilisateur where nomutilisateur='employe2'));
INSERT INTO role(nomrole, utilisateur_idutilisateur)
VALUES('RoleEmploye1',(SELECT idutilisateur from utilisateur where nomutilisateur='employe3'));

INSERT INTO droit(role_idrole)
VALUES (SELECT idrole from role where nomrole='RoleBoss');
INSERT INTO droit(role_idrole)
VALUES (SELECT idrole from role where nomrole='RoleResponsable1');
INSERT INTO droit(role_idrole)
VALUES (SELECT idrole from role where nomrole='RoleEmploye1');


INSERT INTO ADRESSE(numerodebatiment, nomderue, codepostale)
VALUES (250, 'Rue de bois_de_boulogne', 'ABC 123');
INSERT INTO ADRESSE(numerodebatiment, nomderue, codepostale)
VALUES (240, 'Rue de bois_de_boulogne', 'BCD 234');
INSERT INTO ADRESSE(numerodebatiment, nomderue, codepostale)
VALUES (230, 'Rue de bois_de_boulogne', 'CDE 345');

INSERT INTO status(nom)
VALUES('actif');
INSERT INTO status(nom)
VALUES('suspendu');
INSERT INTO status(nom)
VALUES('inactif');


INSERT INTO membre(nom,prenom,numerotelephone,adressecourriel,dateabonnement,status_idstatus,adresse_idadresse)
VALUES('A','membre1','514-123-1234','membre1@exemple.com','2025-06-12',
(SELECT idstatus from status where nom='actif'),(SELECT idadresse from adresse where numerodebatiment=250));

INSERT INTO membre(nom,prenom,numerotelephone,adressecourriel,dateabonnement,status_idstatus,adresse_idadresse)
VALUES('B','membre2','514-123-1234','membre2@exemple.com','2025-08-12',
(SELECT idstatus from status where nom='suspendu'),(SELECT idadresse from adresse where numerodebatiment=240));

INSERT INTO membre(nom,prenom,numerotelephone,adressecourriel,dateabonnement,status_idstatus,adresse_idadresse)
VALUES('C','membre3','514-123-1234','membre2@exemple.com','2021-08-14',
(SELECT idstatus from status where nom='inactif'),(SELECT idadresse from adresse where numerodebatiment=240));


INSERT INTO suspensions(datedebut,datefin,raison,membre_idmembre)
VALUES('2026-09-17','2026-10-07','retard de retour',(SELECT idmembre from membre where nom='B'));
INSERT INTO suspensions(datedebut,datefin,raison,membre_idmembre)
VALUES('2024-05-16',null,'retard de retour a plusieurs reprises',(SELECT idmembre from membre where nom='C'));
INSERT INTO suspensions(datedebut,datefin,raison,membre_idmembre)
VALUES('2026-04-15','2026-05-15','retard de retours',(SELECT idmembre from membre where nom='A'));

INSERT INTO genre(nom)
VALUES('Roman');
INSERT INTO genre(nom)
VALUES('Nouvelle');
INSERT INTO genre(nom)
VALUES('Receuil de poesie');

INSERT INTO maisonedition(nom)
VALUES('ME1');
INSERT INTO maisonedition(nom)
VALUES('ME2');
INSERT INTO maisonedition(nom)
VALUES('ME3');

INSERT INTO etat(nometat)
VALUES('Comme neuf');
INSERT INTO etat(nometat)
VALUES('Bon etat');
INSERT INTO etat(nometat)
VALUES('Endommage');

INSERT INTO auteur(nom)
VALUES('A1');
INSERT INTO auteur(nom)
VALUES('A2');
INSERT INTO auteur(nom)
VALUES('A3');


INSERT INTO livre(titre,datepublication,numeroisbn,description,cheminimagecouverture,estemprunte,genre_idgenre,auteur_idauteur,etat_idetat,maisonedition_idme)
VALUES('T2','1985-05-18',123456,'abcdef','/repo1/fichier2.jpng',1,(SELECT idgenre from genre where nom='Roman'),(SELECT idauteur from auteur where nom='A2'),
(Select idetat from etat where nometat='Comme neuf'),(SELECT idme from maisonedition where nom='ME2'));

INSERT INTO livre(titre,datepublication,description,cheminimagecouverture,estemprunte,genre_idgenre,auteur_idauteur,etat_idetat,maisonedition_idme)
VALUES('T1','1885-05-18','abcdef','/repo1/fichier1.jpng',0,(SELECT idgenre from genre where nom='Nouvelle'),(SELECT idauteur from auteur where nom='A1'),
(Select idetat from etat where nometat='Endommage'),(SELECT idme from maisonedition where nom='ME1'));

INSERT INTO livre(titre,datepublication,numeroisbn,description,cheminimagecouverture,estemprunte,genre_idgenre,auteur_idauteur,etat_idetat,maisonedition_idme)
VALUES('T3','1995-05-18',159487263,'abcdef','/repo1/fichier3.jpng',0,(SELECT idgenre from genre where nom='Roman'),(SELECT idauteur from auteur where nom='A3'),
(Select idetat from etat where nometat='Comme neuf'),(SELECT idme from maisonedition where nom='ME3'));



INSERT INTO emprunt(membre_idmembre,livre_idlivre,datedebut,dateretourprevue,dateretour,enretard,utilisateur_idutilisateur)
values((Select idmembre from membre where nom ='A'),(select idlivre from livre where titre='T2'),'2026-09-25','2026-10-2',null,0,(select idutilisateur from utilisateur where nomutilisateur='employe1'));

INSERT INTO emprunt(membre_idmembre,livre_idlivre,datedebut,dateretourprevue,dateretour,enretard,utilisateur_idutilisateur)
values((Select idmembre from membre where nom ='C'),(select idlivre from livre where titre='T1'),'2023-09-25','2023-10-2','2023-10-28',1,(select idutilisateur from utilisateur where nomutilisateur='employe2'));

INSERT INTO emprunt(membre_idmembre,livre_idlivre,datedebut,dateretourprevue,dateretour,enretard,utilisateur_idutilisateur)
values((Select idmembre from membre where nom ='B'),(select idlivre from livre where titre='T3'),'2026-09-02','2026-09-09','2026-09-17',1,(select idutilisateur from utilisateur where nomutilisateur='employe3'));

