-- Généré par Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   à :        2026-09-24 17:38:48 HAE
--   site :      Oracle Database 21c
--   type :      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE adresse (
    idadresse        GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    numerodebatiment INTEGER NOT NULL,
    nomderue         VARCHAR2(64 CHAR) NOT NULL,
    codepostale      VARCHAR2(64 CHAR) NOT NULL
);


CREATE TABLE auteur (
    idauteur GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom      VARCHAR2(64 CHAR) NOT NULL,
    prenom   VARCHAR2(64 CHAR) NOT NULL
);


CREATE TABLE droit (
    iddroit     GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_idrole INTEGER NOT NULL
);


CREATE TABLE emprunt (
    membre_idmembre           INTEGER NOT NULL,
    livre_idlivre             INTEGER NOT NULL,
    idemprunt                 INTEGER NOT NULL,
    datedebut                 DATE NOT NULL,
    dateretourprevue          DATE NOT NULL,
    dateretour                DATE,
    enretard                  NUMBER NOT NULL,
    utilisateur_idutilisateur INTEGER NOT NULL
);

ALTER TABLE emprunt
    ADD CONSTRAINT emprunt_pk PRIMARY KEY ( membre_idmembre,
                                            livre_idlivre,
                                            idemprunt );

CREATE TABLE etat (
    idetat  INTEGER NOT NULL,
    nometat VARCHAR2(64 CHAR) NOT NULL
);

ALTER TABLE etat ADD CONSTRAINT etat_pk PRIMARY KEY ( idetat );

CREATE TABLE genre (
    idgenre INTEGER NOT NULL,
    nom     VARCHAR2(64 CHAR) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( idgenre );

CREATE TABLE livre (
    idlivre            INTEGER NOT NULL,
    titre              VARCHAR2(256 CHAR) NOT NULL,
    datepublication    DATE NOT NULL,
    numeroisbn         INTEGER,
    description        VARCHAR2(256 CHAR) NOT NULL,
    imagecouverture    BLOB NOT NULL,
    genre_idgenre      INTEGER NOT NULL,
    auteur_idauteur    INTEGER NOT NULL,
    etat_idetat        INTEGER NOT NULL,
    maisonedition_idme INTEGER NOT NULL,
    estemprunter       NUMBER NOT NULL
);

ALTER TABLE livre ADD CONSTRAINT livre_pk PRIMARY KEY ( idlivre );

CREATE TABLE maisonedition (
    idme INTEGER NOT NULL,
    nom  VARCHAR2(64) NOT NULL
);

ALTER TABLE maisonedition ADD CONSTRAINT maisonedition_pk PRIMARY KEY ( idme );

CREATE TABLE membre (
    idmembre          INTEGER NOT NULL,
    nom               VARCHAR2(64 CHAR) NOT NULL,
    prenom            VARCHAR2(64 CHAR) NOT NULL,
    adresse           VARCHAR2(100 CHAR) NOT NULL,
    numerotelephone   VARCHAR2(20 CHAR) NOT NULL,
    adressecourriel   VARCHAR2(100 CHAR) NOT NULL,
    dateabonnement    DATE NOT NULL,
    status_idstatus   INTEGER NOT NULL,
    adresse_idadresse INTEGER NOT NULL
);

ALTER TABLE membre ADD CONSTRAINT membre_pk PRIMARY KEY ( idmembre );

CREATE TABLE role (
    idrole                    INTEGER NOT NULL,
    nomrole                   VARCHAR2(64) NOT NULL,
    utilisateur_idutilisateur INTEGER NOT NULL
);

ALTER TABLE role ADD CONSTRAINT role_pk PRIMARY KEY ( idrole );

CREATE TABLE "session" (
    idsession                 INTEGER NOT NULL,
    utilisateur_idutilisateur INTEGER NOT NULL
);

ALTER TABLE "session" ADD CONSTRAINT session_pk PRIMARY KEY ( idsession );

CREATE TABLE status (
    idstatus INTEGER NOT NULL,
    nom      VARCHAR2(64 CHAR) NOT NULL
);

ALTER TABLE status ADD CONSTRAINT status_pk PRIMARY KEY ( idstatus );

CREATE TABLE suspensions (
    idsuspension    INTEGER NOT NULL,
    datedebut       DATE NOT NULL,
    datefin         DATE NOT NULL,
    raison          VARCHAR2(256 CHAR) NOT NULL,
    membre_idmembre INTEGER NOT NULL
);

ALTER TABLE suspensions ADD CONSTRAINT suspensions_pk PRIMARY KEY ( idsuspension );

CREATE TABLE utilisateur (
    idutilisateur  INTEGER NOT NULL,
    nomutilisateur VARCHAR2(64 CHAR) NOT NULL,
    motdepasse     VARCHAR2(64) NOT NULL
);

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( idutilisateur );

ALTER TABLE droit
    ADD CONSTRAINT droit_role_fk
        FOREIGN KEY ( role_idrole )
            REFERENCES role ( idrole )
                ON DELETE CASCADE;

ALTER TABLE emprunt
    ADD CONSTRAINT emprunt_livre_fk
        FOREIGN KEY ( livre_idlivre )
            REFERENCES livre ( idlivre )
                ON DELETE CASCADE;

ALTER TABLE emprunt
    ADD CONSTRAINT emprunt_membre_fk
        FOREIGN KEY ( membre_idmembre )
            REFERENCES membre ( idmembre )
                ON DELETE CASCADE;

ALTER TABLE emprunt
    ADD CONSTRAINT emprunt_utilisateur_fk
        FOREIGN KEY ( utilisateur_idutilisateur )
            REFERENCES utilisateur ( idutilisateur )
                ON DELETE CASCADE;

ALTER TABLE livre
    ADD CONSTRAINT livre_auteur_fk
        FOREIGN KEY ( auteur_idauteur )
            REFERENCES auteur ( idauteur )
                ON DELETE CASCADE;

ALTER TABLE livre
    ADD CONSTRAINT livre_etat_fk
        FOREIGN KEY ( etat_idetat )
            REFERENCES etat ( idetat )
                ON DELETE CASCADE;

ALTER TABLE livre
    ADD CONSTRAINT livre_genre_fk
        FOREIGN KEY ( genre_idgenre )
            REFERENCES genre ( idgenre )
                ON DELETE CASCADE;

ALTER TABLE livre
    ADD CONSTRAINT livre_maisonedition_fk
        FOREIGN KEY ( maisonedition_idme )
            REFERENCES maisonedition ( idme )
                ON DELETE CASCADE;

ALTER TABLE membre
    ADD CONSTRAINT membre_adresse_fk
        FOREIGN KEY ( adresse_idadresse )
            REFERENCES adresse ( idadresse )
                ON DELETE CASCADE;

ALTER TABLE membre
    ADD CONSTRAINT membre_status_fk
        FOREIGN KEY ( status_idstatus )
            REFERENCES status ( idstatus )
                ON DELETE CASCADE;

ALTER TABLE role
    ADD CONSTRAINT role_utilisateur_fk
        FOREIGN KEY ( utilisateur_idutilisateur )
            REFERENCES utilisateur ( idutilisateur )
                ON DELETE CASCADE;

ALTER TABLE "session"
    ADD CONSTRAINT session_utilisateur_fk
        FOREIGN KEY ( utilisateur_idutilisateur )
            REFERENCES utilisateur ( idutilisateur )
                ON DELETE CASCADE;

ALTER TABLE suspensions
    ADD CONSTRAINT suspensions_membre_fk
        FOREIGN KEY ( membre_idmembre )
            REFERENCES membre ( idmembre )
                ON DELETE CASCADE;

CREATE SEQUENCE adresse_idadresse_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER adresse_idadresse_trg BEFORE
    INSERT ON adresse
    FOR EACH ROW
    WHEN ( new.idadresse IS NULL )
BEGIN
    :new.idadresse := adresse_idadresse_seq.nextval;
END;
/

CREATE SEQUENCE auteur_idauteur_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER auteur_idauteur_trg BEFORE
    INSERT ON auteur
    FOR EACH ROW
    WHEN ( new.idauteur IS NULL )
BEGIN
    :new.idauteur := auteur_idauteur_seq.nextval;
END;
/

CREATE SEQUENCE droit_iddroit_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER droit_iddroit_trg BEFORE
    INSERT ON droit
    FOR EACH ROW
    WHEN ( new.iddroit IS NULL )
BEGIN
    :new.iddroit := droit_iddroit_seq.nextval;
END;
/

CREATE SEQUENCE emprunt_idemprunt_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER emprunt_idemprunt_trg BEFORE
    INSERT ON emprunt
    FOR EACH ROW
    WHEN ( new.idemprunt IS NULL )
BEGIN
    :new.idemprunt := emprunt_idemprunt_seq.nextval;
END;
/

CREATE SEQUENCE etat_idetat_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER etat_idetat_trg BEFORE
    INSERT ON etat
    FOR EACH ROW
    WHEN ( new.idetat IS NULL )
BEGIN
    :new.idetat := etat_idetat_seq.nextval;
END;
/

CREATE SEQUENCE genre_idgenre_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER genre_idgenre_trg BEFORE
    INSERT ON genre
    FOR EACH ROW
    WHEN ( new.idgenre IS NULL )
BEGIN
    :new.idgenre := genre_idgenre_seq.nextval;
END;
/

CREATE SEQUENCE livre_idlivre_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER livre_idlivre_trg BEFORE
    INSERT ON livre
    FOR EACH ROW
    WHEN ( new.idlivre IS NULL )
BEGIN
    :new.idlivre := livre_idlivre_seq.nextval;
END;
/

CREATE SEQUENCE maisonedition_idme_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER maisonedition_idme_trg BEFORE
    INSERT ON maisonedition
    FOR EACH ROW
    WHEN ( new.idme IS NULL )
BEGIN
    :new.idme := maisonedition_idme_seq.nextval;
END;
/

CREATE SEQUENCE membre_idmembre_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER membre_idmembre_trg BEFORE
    INSERT ON membre
    FOR EACH ROW
    WHEN ( new.idmembre IS NULL )
BEGIN
    :new.idmembre := membre_idmembre_seq.nextval;
END;
/

CREATE SEQUENCE role_idrole_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER role_idrole_trg BEFORE
    INSERT ON role
    FOR EACH ROW
    WHEN ( new.idrole IS NULL )
BEGIN
    :new.idrole := role_idrole_seq.nextval;
END;
/

CREATE SEQUENCE session_idsession_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER session_idsession_trg BEFORE
    INSERT ON "session"
    FOR EACH ROW
    WHEN ( new.idsession IS NULL )
BEGIN
    :new.idsession := session_idsession_seq.nextval;
END;
/

CREATE SEQUENCE status_idstatus_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER status_idstatus_trg BEFORE
    INSERT ON status
    FOR EACH ROW
    WHEN ( new.idstatus IS NULL )
BEGIN
    :new.idstatus := status_idstatus_seq.nextval;
END;
/

CREATE SEQUENCE suspensions_idsuspension_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER suspensions_idsuspension_trg BEFORE
    INSERT ON suspensions
    FOR EACH ROW
    WHEN ( new.idsuspension IS NULL )
BEGIN
    :new.idsuspension := suspensions_idsuspension_seq.nextval;
END;
/

CREATE SEQUENCE utilisateur_idutilisateur_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER utilisateur_idutilisateur_trg BEFORE
    INSERT ON utilisateur
    FOR EACH ROW
    WHEN ( new.idutilisateur IS NULL )
BEGIN
    :new.idutilisateur := utilisateur_idutilisateur_seq.nextval;
END;
/



-- Rapport récapitulatif d'Oracle SQL Developer Data Modeler : 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          14
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         14
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
